### ISSUE TITLE
Fields with question mark in SepaRemittenceInformation cause error

### ISSUE THREAD

**Issue by kpi6288** [programmersdigest/MT940Parser#1]
I received a file with a question mark in the MREF field: 

... ?21MREF+5LT?SI6SNX...?22

The question mark in front of SI causes an exception "System.IO.InvalidDataException: Unknown field code: SI".

**Comment by programmersdigest** [comment]
The separator of the information field is defined after the transaction code. From what you show, the separator is "?" and correctly detected as such. So the parser will indeed try to parse "SI6SNX..." as a data field. To me, the specifications do not clearly state whether data like this is valid, however, so I would assume it is.

The problem could be attacked by adding an additional check after having found the separator in AdditionalInfoParser.cs line 153: Check whether the separator is followed by one of the valid field codes defined in DetectFieldCode(). If it is not, the separator should be ignored. I will look into this.
